limit_req_zone $binary_remote_addr zone=tg_limit:10m rate=10r/s;

server {
    listen 80;
    client_max_body_size 100k;

    location /health {
        proxy_pass http://terraguard:8000/health;
    }

    location / {
        limit_req zone=tg_limit burst=20 nodelay;

        if ($http_x_rapidapi_proxy_secret = "") {
            return 403;
        }

        proxy_pass http://terraguard:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-RapidAPI-Proxy-Secret $http_x_rapidapi_proxy_secret;
    }
}
